MYSQL_USER: ssafy
MYSQL_PASSWORD: ssafy207
MYSQL_URL: jdbc:mysql://ssafy207.duckdns.org:3306/ijoa_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8

---

spring:
  config:
    activate:
      on-profile: dev

MYSQL_USER: ssafy
MYSQL_PASSWORD: ssafy
MYSQL_URL: jdbc:mysql://localhost:3306/ijoa_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8

---

spring:
  config:
    activate:
      on-profile: server

MYSQL_USER: ssafy
MYSQL_PASSWORD: ssafy207
MYSQL_URL: jdbc:mysql://ssafy207.duckdns.org:3306/ijoa_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8