spring:
  profiles:
#    include: dev, env  #dev
    include: server, env  #server

  ## 이미지 파일 크기 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      #enabled: true  # multipart 에 대한 일을 처리하게끔 해준다(기본값)

  ## swagger 에러 해결
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  ## spring boot 2.5 이상 버전의 경우 자동으로 실행되지 않아
  ## spring.sql.init.mode=always 프로퍼티 값을 입력해주어야 한다.
  sql:
    init:
      mode: never
#      mode: always


server:
  ## UTF-8 인코딩 설정
  servlet:
    encoding:
      charset: UTF-8
      force: true

## AWS S3를 연동한 프로젝트에서 발생하는 오류 방지
## 프로젝트 배포시 기본으로 CloudFormation 구성을 시작하기 때문에
## 설정한 CloudFormation이 없으면 프로젝트 실행이 되지 않음.
## 해당 기능을 사용하지 않도록 false로 설정.
cloud:
  aws:
    stack:
      auto: false



